### ISSUE TITLE
new work on composite primary key

### ISSUE THREAD

**Issue by auvipy** [dcramer/django-compositepks#3]
https://github.com/django/django/pull/4553

If have any interest

**Comment by kmmbvnr** [comment]
please stop use the issue tracker as a chat

**Comment by jorgempy** [comment]
+1

**Comment by stefanplug** [comment]
+1

**Comment by clovis818** [comment]
+1

**Comment by bkaluza** [comment]
+1

**Comment by auvipy** [comment]
I have started work on composite pk and related orm improvement so closing this issue
